name: Test and deploy

on:
  push:

jobs:
  use-reusable:
    uses: DevTips-Daily/github-action-tutorial-1/.github/workflows/reusable-ci.yml@main
    with:
      node-version: '20'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install

      - name: Deplpoy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
        env: 
          VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
