name: reusable CI

on:
  workflow_call:
    inputs: 
      node-version:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: macOSARM
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - run: |
          npm install
          npm test