name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 19, 20]
        exclude:
          - os: windows-latest
            node: 18
          - os: ubuntu-latest
            node: 19
    name: OS ${{ matrix.os }} and node version ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Run tests
        run: |
          npm install
          npm test
